### Obtener Carrito
GET http://localhost:3001/api/carrito
Accept: application/json
Authorization: Bearer TOKEN

### Añadir/Actualizar Ítem en Carrito
POST http://localhost:3001/api/carrito/items
Content-Type: application/json
Accept: application/json
Authorization: Bearer TOKEN

{
  "juegoId": 1,   
  "cantidad": 2   
}

### Eliminar Ítem Específico del Carrito
DELETE http://localhost:3001/api/carrito/items/1
Accept: application/json
Authorization: Bearer TOKEN

### Vaciar Carrito
DELETE http://localhost:3001/api/carrito
Accept: application/json
Authorization: Bearer TOKEN