### Obtener todos
GET http://localhost:3001/api/juegos

### Obtener por ID
GET http://localhost:3001/api/juegos/1

### Crear nuevo juego
POST http://localhost:3001/api/juegos
Content-Type: application/json

{
  "Nombre": "Elden Ring",
  "Descripcion": "Un RPG de acción en un mundo abierto.",
  "DescripcionLarga": "Elden Ring es un juego de rol de acción con un vasto mundo abierto y una narrativa épica desarrollada por FromSoftware.",
  "Precio": 1.99,
  "Oferta": 15,
  "Categoria_CategoriaID": 1,
  "Stock": 50,
  "Rating": 4.8,
  "Imagen": "https://example.com/eldenring.jpg",
  "TrailerURL": "https://www.youtube.com/watch?v=E3Huy2cdih0",
  "Galeria": [
    "https://example.com/eldenring1.jpg",
    "https://example.com/eldenring2.jpg",
    "https://example.com/eldenring3.jpg"
  ],
  "Caracteristicas": ["Multijugador", "Mundo abierto", "Combate desafiante"],
  "Lanzamiento": "2022-02-25T00:00:00.000Z",
  "Estado": true
}

### Actualizar
PUT http://localhost:3001/api/juegos/1
Content-Type: application/json

{
  "Stock": 80,
  "Precio": 179.99,
  "Estado": true
}

### Eliminar
DELETE http://localhost:3001/api/juegos/4

### Filtrar
GET http://localhost:3001/api/juegos/filtros/buscar?nombre=elden&categoria=1&plataforma=PC