### Obtener todos
GET http://localhost:3001/api/juegos

### Obtener por ID
GET http://localhost:3001/api/juegos/1

### Crear nuevo juego
POST http://localhost:3001/api/juegos
Content-Type: application/json

{
  "nombre": "Elden Ring",
  "titulo": "Elden Ring",
  "descripcion": "Un RPG de acción en un mundo abierto.",
  "descripcionLarga": "Elden Ring es un juego de rol de acción con un vasto mundo abierto y una narrativa épica desarrollada por FromSoftware.",
  "precio": 1.99,
  "descuento": 15,
  "plataformas": ["PC", "PS5", "XBOX"],
  "categoria": "RPG",
  "stock": 50,
  "rating": 4.8,
  "imagen": "https://example.com/eldenring.jpg",
  "trailerUrl": "https://www.youtube.com/watch?v=E3Huy2cdih0",
  "generos": ["Acción", "Aventura", "Fantasía"],
  "caracteristicas": ["Multijugador", "Mundo abierto", "Combate desafiante"],
  "lanzamiento": "2022-02-25T00:00:00.000Z",
  "galleryImages": [
    "https://example.com/eldenring1.jpg",
    "https://example.com/eldenring2.jpg",
    "https://example.com/eldenring3.jpg"
  ]
}


### Actualizar
PUT http://localhost:3001/api/juegos/1
Content-Type: application/json

{
  "stock": 80,
  "precio": 179.99
}

### Eliminar
DELETE http://localhost:3001/api/juegos/4

### Filtrar
GET http://localhost:3001/api/juegos/filtros/buscar?nombre=elden&categoria=RPG&plataforma=PC
