GET http://localhost:3001/api/admin/users
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTEsInRpcG8iOnRydWUsImlhdCI6MTc1MTUwMDI1MCwiZXhwIjoxNzUxNTAzODUwfQ.9qTj18bDjXRnl659qlTNgZPa6EzdAEwzhmCtaWQwu3E