### Obtener Todas las Noticias
GET http://localhost:3001/api/noticia
Accept: application/json
Authorization: Bearer TOKEN

### Obtener Noticia por ID
GET http://localhost:3001/api/noticia/4
Accept: application/json
Authorization: Bearer TOKEN

### Crear Noticia 
POST http://localhost:3001/api/noticia
Content-Type: application/json
Accept: application/json
Authorization: Bearer TOKEN

{
  "Titulo": "¡Grandes Novedades de Verano!",
  "Descripcion": "Descubre los eventos y ofertas más emocionantes que llegan a tus juegos favoritos.",
  "Foto": "https://example.com/noticia_verano.jpg"
}

### Actualizar Noticia
PUT http://localhost:3001/api/noticia/2
Content-Type: application/json
Accept: application/json
Authorization: Bearer TOKEN

{
  "Titulo": "Noticia Actualizada: ¡Parche 1.2 Ya Disponible!",
  "Descripcion": "Conoce todos los cambios y mejoras del último parche para tu juego preferido.",
  "Foto": "https://example.com/parche_noticia.jpg"
}

### Eliminar Noticia 
DELETE http://localhost:3001/api/noticia/2
Accept: application/json
Authorization: Bearer TOKEN