### Registro de usuario
POST http://localhost:3001/api/usuarios/registro
Content-Type: application/json

{
  "nickname": "gamer123",
  "correo": "gamer@mail.com",
  "contrasena": "12345678",
  "name": "Gamer Pro",
  "imagen": "https://example.com/avatar.jpg"
}

### Iniciar sesión
POST http://localhost:3001/api/usuarios/login
Content-Type: application/json

{
  "correo": "gamer@mail.com",
  "contrasena": "12345678"
}

### Obtener todos los usuarios
GET http://localhost:3001/api/usuarios

### Editar un usuario
PUT http://localhost:3001/api/usuarios/1
Content-Type: application/json

{
  "name": "Gamer Editado",
  "nickname": "proGamer"
}

### Eliminar un usuario
DELETE http://localhost:3001/api/usuarios/5
