### ✅ Registro exitoso
POST http://localhost:3001/api/usuarios/registro
Content-Type: application/json

{
  "nickname": "gamerx",
  "correo": "gamerx@email.com",
  "contrasena": "12345678",
  "confirmarContrasena": "12345678",
  "name": "Gamer X",
  "imagen": "https://img.com/avatar.png"
}

### ❌ Error: campos vacíos
POST http://localhost:3001/api/usuarios/registro
Content-Type: application/json

{
  "nickname": "",
  "correo": "",
  "contrasena": "",
  "confirmarContrasena": "",
  "name": ""
}

### ❌ Error: correo inválido
POST http://localhost:3001/api/usuarios/registro
Content-Type: application/json

{
  "nickname": "player2",
  "correo": "sin-arroba.com",
  "contrasena": "12345678",
  "confirmarContrasena": "12345678",
  "name": "Sin Correo"
}

### ❌ Error: contraseñas no coinciden
POST http://localhost:3001/api/usuarios/registro
Content-Type: application/json

{
  "nickname": "nuevoNick",
  "correo": "nuevo@email.com",
  "contrasena": "12345678",
  "confirmarContrasena": "87654321",
  "name": "Diferente Pass"
}

### ❌ Error: duplicado de nickname o correo
POST http://localhost:3001/api/usuarios/registro
Content-Type: application/json

{
  "nickname": "gamerx",
  "correo": "gamerx@email.com",
  "contrasena": "12345678",
  "confirmarContrasena": "12345678",
  "name": "Repetido"
}