### Registrar un nuevo usuario
GET http://localhost:3001/api/estadisticas/total-usuarios
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc3VhcmlvSUQiOjIsIkFkbWluIjp0cnVlLCJpYXQiOjE3NTI0MTU1OTcsImV4cCI6MTc1MjQxOTE5N30.qmedlB1Ppfbw5NUJDUTSk96IQHzgKhCgbMB96sPXprc